export const ADD_STUDENT = "ADD_STUDENT";
export const UPLOAD_STUDENT = "UPLOAD_STUDENT"
export const DISPLAY_STUDENT  = "DISPLAY_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT  = "DELETE_STUDENT";

